---
layout: post
title: ES6 Promise
feature-img: "assets/img/portfolio/cabin.png"
img: "assets/img/portfolio/cabin.png"
tags: [project 1, technical proficiency]
date: 2019-09-01
color: brown
---

I can always see the after function call .then .catch When I try to use some Javascript library. Basically I know that means when the function was called later on have two ways to do continuously neight result is good or get some error need catch. But what is exactly going on under the hook? I think it is time to dig deep for this. I just record some sample example here.

First of all, I created a traditional Javascript function below to show the data:
```javascript
// declare a array contains two person in there
const data = [{ name: "aemon", age: 18 }, { name: "dora", age: 20 }];

// declare a function to add new person and includes callback function
// when add new person finished call it to show data inside the HTML body tag
function addData(person, callback) {
setTimeout(() => {
    data.push(person);
    callback(); // call callback function
}, 2000);
}

// declare callback function
// get data then put in the body tag
function getData() {
setTimeout(() => {
    let output = "";
    data.forEach(person => {
    output += `<li>${person.name} - ${person.age}</li>`;
    });
    document.body.innerHTML = output;
}, 1000);
}

// call add new peron function
// pass in a new person and callback function name
addData({ name: "adon", age: 21 }, getData);
```
This a piece of code will get all three person infomation to show on the page

Secondly, I will do some changing on the code above:
```javascript
// add new person function compare with above function 
// I added the Promis syntax and take out of the callback function
// and check the error then call resovle, reject in different scence
function addDataWithPromise(person) {
return new Promise((resolve, reject) => {
    setTimeout(() => {
    data.push(person);
    const error = false;
    if (!error) {
        resolve();
    } else {
        reject("Something went wroing");
    }
    }, 2000);
});
}

// when call add new person function we call it
// and use .then .catch chain to do more clear flow
addDataWithPromise({ name: "auther", age: 25 })
.then(getData)
.catch(err => {
    console.log(err);
});
```

Finaly, I don't know how to describe the Promise clearly with English. So just grab a conclusion from internet. Promises are a pattern that greatly simplifies asynchronous programming by making the code look synchronous and avoid problems associated with callbacks. Promise also is a object, if we use browser debug we can see the promise like this:
```bash
Promise {<resolved>: "Hello"}
__proto__: Promise
catch: ƒ catch()
constructor: ƒ Promise()
finally: ƒ finally()
then: ƒ then()
Symbol(Symbol.toStringTag): "Promise"
__proto__: Object
[[PromiseStatus]]: "resolved"
[[PromiseValue]]: "Hello"
```
You can see here the promise was returned by browser which includes constructor, then, catch, finally function. And there is a exapmle that how to implement the promise.
https://www.promisejs.org/implementing/